### ISSUE TITLE
M5: Creating a dynamic policies resource crashes the AF 

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#127]
# Description
When creating a dynamic policies resource via the M5 interface, I am running into an issue that the Application Function is crashing. Note that I have **no** Open5GS core connected but enabled in the config.

## AF configuration
````
msaf:
    open5gsIntegration: true    
    sbi:
      - addr: 127.0.0.22
        port: 7777
    m1:
      - addr: 0.0.0.0
        port: 5678
    m5:
      - addr: 0.0.0.0
        port: 7778
    maf:
      - addr: 127.0.0.25
        port: 7777
    applicationServers:
      - canonicalHostname: localhost
        urlPathPrefixFormat: /m4d/provisioning-session-{provisioningSessionId}/
        m3Port: 7777
    certificateManager: /usr/local/libexec/rt-5gms/self-signed-certmgr
    serverResponseCacheControl:
      - maxAge: 60
        m1ProvisioningSessions: 60
        m1ContentHostingConfigurations: 60
        m1ServerCertificates: 60
        m1ContentProtocols: 86400
        m1ConsumptionReportingConfiguration: 60
        m5ServiceAccessInformation: 60
    dataCollectionDir: /var/local/log/open5gs/reports
    offerNetworkAssistance: true
    networkAssistance:
      deliveryBoost:
        minDlBitRate: 1 Mbps
        boostPeriod: 30
````

### 1. M1: Create a provisioning session
Payload:

````json
{
    "aspId": "aspId",
    "appId": "appId",
    "provisioningSessionType": "DOWNLINK"
}
````

### 2. M1: Create a policy template
Payload:
````json
{
    "externalReference": "externalReference"
}
````

### 3. M1: Update the policy template
Payload
````json
{
    "externalReference": "externalReferenceUpdated2",
    "policyTemplateId": "editedId",
    "state": "INVALID",
    "stateReason": {
        "type": "type"
    },
    "qoSSpecification": {
        "qosReference": "qosReference",
        "maxBtrUl": "560 Kbps",
        "maxBtrDl": "500 Kbps",
        "maxAuthBtrUl": "400 Kbps",
        "maxAuthBtrDl": "300 Kbps",
        "defPacketLossRateDl": 1,
        "defPacketLossRateUl": 1
    },
    "applicationSessionContext": {
        "sliceInfo": {
            "sst": 200,
            "sd": "000000"
        },
        "dnn": "test"
    },
    "chargingSpecification": {
        "sponId": "sponId",
        "sponStatus": "SPONSOR_ENABLED_INVALID",
        "gpsi": [
            "msisdn-12345"
        ]    
    }
}
````

### 4. M5: Create a dynamic policies resource
Payload
````json
{
    "serviceDataFlowDescriptions": [
        {
            "direction": "direction"
        }
    ],
    "provisioningSessionId": "{{provisioning_session_id}}",
    "policyTemplateId": "{{policy_template_id}}"
}
```` 

### 5. Resulting error on AF
````
01/22 10:18:37.344: [sbi] FATAL: An HTTP request was received, but the HTTP response is missing. (../subprojects/open5gs/lib/sbi/mhd-server.c:177)
01/22 10:18:37.344: [sbi] FATAL: Please send the related pcap files for this case. (../subprojects/open5gs/lib/sbi/mhd-server.c:179)
01/22 10:18:37.344: [sbi] FATAL: session_timer_expired: should not be reached. (../subprojects/open5gs/lib/sbi/mhd-server.c:183)
01/22 10:18:37.345: [core] FATAL: backtrace() returned 7 addresses (../subprojects/open5gs/lib/core/ogs-abort.c:37)
/usr/local/lib/x86_64-linux-gnu/libogssbi.so.2(+0x29951) [0x7fb62efd8951]
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(ogs_timer_mgr_expire+0x154) [0x7fb62ef7e102]
/usr/local/bin/open5gs-msafd(+0x8c6f) [0x559f23ed9c6f]
/usr/local/lib/x86_64-linux-gnu/libogscore.so.2(+0x11b23) [0x7fb62ef7eb23]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fb62e294ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7fb62e326850]
Aborted
````
