### ISSUE TITLE
QoE Metrics Reporting - M1 Provisioning - samplingPeriod can be negative

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#146]
## Description
TS 26.512 Table 7.8.3-1 defines the `samplingPeriod` as follows:

> The time interval the 5GMS Client should wait between sampling the QoE metrics specified by this metrics reporting configuration.

In my opinion, a negative value does not make sense here, although it is not explicitly mentioned in the specification. However, the type of the `samplingPeriod` is `DurationSec` which is defined in TS29571_CommonData as : 

````yaml
    DurationSec:
      type: integer
      description: indicating a time in seconds.
````

A negative time in seconds seems to be unreasonable. I suggest to return an error in case a negative value for `samplingPeriod` is provided.
